### ISSUE TITLE
AC3 passthrough doesn't work on Amlogic S805

### ISSUE THREAD

**Issue by jirkav77** [koying/SPMC#114]
I have an Amlogic S805 device (Rikomagic MK05). SPMC 16.1.1 works on it except of AC3 passthrough - only loud noisy sound is hearable when passthrough enabled. Receiver shows, that the input stream is PCM not AC3 (even if Ac3 is enabled in SPMC settings). 

Note that it works correctly with SPMC 15 as well as with bundled KODI 14.1.

Thank you for advice.

**Comment by jirkav77** [comment]
I can provide additional info, logs, etc.  if you will need it. Thank you.

**Comment by thai2000** [comment]
I have the same problems on my UGOOS UT3S .; No DTS and DD 5.1

**Comment by jirkav77** [comment]
It looks like SPMC doesn't send some info/flag that the output stream is AC3 encoded - the receiver (as well as the TV-set) thinks that the stream is PCM - result is a noise...

**Comment by heymoe** [comment]
This sounds like the same problem I'm having. Here is my setup:

Android TV Device: Shield TV (16GB) running v3.0 (Marshmallow)
SPMC Version: Latest PlayStore version (assuming 16.1.2)

I also have a Turtle Beach Audio Advantage Micro II USB-DAC plugged in to one of the USB3 ports to get an optical SPDIF output since my receiver does not support HDMI. My Shield's HDMI port is connected directly to the TV.

Before switching to the Shield TV I was running Kodi on a HTPC which is connected to my receiver via optical SPDIF for audio and HDMI directly to my TV.  With this setup I could play AC3, DTS and PCM audio without any problem. My receiver has auto detect enabled on the optical input so it can switch to the correct decoder without me having to tell it what type of audio stream I'm sending it. It should also be noted my receiver does not support any of the newer audio HD formats so I'm just talking about regular ole AC3 and DTS. 

When running Kodi and now SPMC to the Shield TV, PCM and DTS audio get auto detected just fine by my receiver but when I play AC3 audio I get basically static, pink noise, white noise, whatever you want to call it (stayed in PCM mode). If I change the SPDIF port on my receiver from auto detect to AC3 only, the receiver decodes the audio just fine. 

So as jirkav77 just mentioned, it seems that some sort of info tag / flag / meta or whatever isn't being sent with the bit stream that is allow my receiver to auto detect the stream as AC3.

This has been a problem with the Shield TV running v2.1 and the new v3.0 code. Also with Kodi v15 and v16 from the PlayStore on both v2.1 and v3.0. I've only run SPMC while on v3.0

**Comment by LarsNorgaard** [comment]
Also same problem here, but on my Amlogic 802 tv box. Almost seems like the problem we had a couple of years ago, where the handshake to the receiver messed up.

**Comment by thai2000** [comment]
Indeed .. it switches 2.0 and 5.1 ...

Verzonden vanaf mijn Samsung Galaxy S6 
-------- Oorspronkelijk bericht --------Van: LarsNorgaard notifications@github.com Datum: 26/03/16  18:33  (GMT+01:00) Aan: koying/SPMC SPMC@noreply.github.com Cc: thai2000 adriaense@telenet.be Onderwerp: Re: [SPMC] AC3 passthrough doesn't work on Amlogic S805 (#114) 
Also same problem here, but on my Amlogic 802 tv box. Almost seems like the problem we had a couple of years ago, where the handshake to the receiver messed up.

**Comment by mandepsi** [comment]
my M8s (amlogic 812, android 4.4.2) has also same Problem with passthrough over HDMI. No DTS and no DD 5.1 but only loud noisy sound is hearable when passthrough enabled. I use KODI v16 at the same time without this problem.

**Comment by thai2000** [comment]
I can only use kodi 15.2 rc for good Digital sound .. all other give problems on 4 boxes with android.

Verzonden vanaf mijn Samsung Galaxy S6 
-------- Oorspronkelijk bericht --------Van: mandepsi notifications@github.com Datum: 28/03/16  03:49  (GMT+01:00) Aan: koying/SPMC SPMC@noreply.github.com Cc: thai2000 adriaense@telenet.be Onderwerp: Re: [SPMC] AC3 passthrough doesn't work on Amlogic S805 (#114) 
my M8s (amlogic 812, android 4.4.2) has also same Problem with passthrough over HDMI. No DTS and no DD 5.1 but only loud noisy sound is hearable when passthrough enabled. I use KODI v16 at the same time without this problem.

**Comment by jupiler5** [comment]
I have exactely the same problem with my Minix Neo X8-H plus (Amlogic S812 / Android 4.4.2 / SPMC v16.1-2): Only loud noisy sound is hearable when passthrough enabled (connected to my amplifier over optical fibre).
Sound works perfectly with Kodi v16.0 (official version).
I tried to ways to configure SPMC: "manual config" and by copying from my Kodi cofiguration (with Backup add-on). Both don't work as I enable passthrough.

I tried SPMC v16.1.1 and v16.1.0, the problem was already there.
Tried SPMC v15.0.0 and no problem

If I may have SPMC v16.0 APK, I could compare it with Kodi Official release v16.0

**Comment by mandepsi** [comment]
with this beta version works again: 

http://download.semperpax.com/spmc/android-arm/SPMC-20160330-59124a3-spmc-jarvis-armeabi-v7a.apk

thanks

**Comment by heymoe** [comment]
Sadly, I can no longer test this issue since I decided to brute force a solution by upgrading my receiver a week ago. It was definitely the more expensive solution but I'm happy to report that the new receiver isn't having any problems auto detecting any for the audio formats I've thrown at it so far.

**Comment by jupiler5** [comment]
Thank you mandepsi ! That works !

**Comment by thai2000** [comment]
Now I  have sound but only stereo . No DTS or DOLBY 5.1...

**Comment by jupiler5** [comment]
Concerning me, I have DTS and Dolby Digital (both tested)

Checked: "Enable passthrough", "Dolby Digital (AC3) capable receiver", "Enable Dolby Digital (AC3 transcoding" and "DTS capable receiver"
Unchecked: "Support 8 channel DTS-HD audio decoding"

**Comment by thai2000** [comment]
I don't see these options ..only Android pcm .. anders iets.. Raw passthrough

**Comment by thai2000** [comment]
I tested with the spmc from the beta link

**Comment by thai2000** [comment]
The only version that give for me DTS and dd5.1 is kodi 15.2 rc 1.. all other have for me no good audio

**Comment by thai2000** [comment]
By the way I have an ugoos ut3s box

**Comment by mandepsi** [comment]
it works for my 
Beelink MiniMX (amlogic s905, lollipop 5.1.1)
M8s (amlogic 812, android 4.4.2) and
MXQ (amlogic 805, android 4.4.2)

BTW only IEC but not RAW

**Comment by koying** [comment]
RAW is actually only useful for Marshmallow, and then again for the devices implementing correctly.
Bottom-line: Shield ;)

**Comment by thai2000** [comment]
Before spmc 14.2 worked for me with DTS and DD5.1 Audio .. after Android update to 5.1.1 it works no More?? Maybe it is an android problem ..

**Comment by mandepsi** [comment]
do not update. make a clean install.

**Comment by thai2000** [comment]
I did  ...

**Comment by thai2000** [comment]
Clean install.. all I get is noise ...  no digitale audio

**Comment by koying** [comment]
Ugoo UT3S is RK. RK needs hacks to get even IEC PT working (no kidding ;) )

**Comment by thai2000** [comment]
How can I do that ??

**Comment by koying** [comment]
You can't.
I anyway OT, as the original issue is solved.

**Comment by jirkav77** [comment]
Version 16.2.0 works perfectly on my Amlogic box. Thank you very much, Koying.
