### ISSUE TITLE
MySQL database name problem

### ISSUE THREAD

**Issue by ButtaJones** [koying/SPMC#1158]
I'm trying to connect to my Krypton database called MyVideos107. When I add it to the SPMC MySQL settings it adds "99" to it. So MyVideos107 becomes MyVideos10799. If I leave it blank it tries to create MyVideos99. Am I doing something wrong? Can this be fixed without making changes to my current database?

[Log](https://pastebin.com/T5a8RjTT)

**Comment by BigOkie** [comment]
It's because you're using SPMC v 16.7; the numbers after the DB name indicate the db version, which are tied to the version of SPMC/Kodi you are using.  Krypton uses DB version 107 and there will be differences between SPMC v16 (which uses DB version 99) and Krypton.  You cannot mix database versions.
