### ISSUE TITLE
Passthrough RAW Outputting DTS as PCM (16.2.1)

### ISSUE THREAD

**Issue by ghost** [koying/SPMC#121]
I wonder if someone can help me please.

I have a file Frozen 2013 BluRay 1080p DTS-HD x264.mkv

If i play it with Passthrough IEC and DD & DTS enabled my Amp shows the file as playing DTS
Log: http://pastebin.com/nL0A6SQ6

If i play it with Passthrough RAW with DD & DTS enabled the amp shows it as PCM.
Log: http://pastebin.com/Ndrfdstd

If i enable DTS-HD on Passthrough RAW I get no sound at all.

Anyone able to help or do i need a log?

I am using SPMC 16.1.2 on an Nvidia Shield 3.0 Marshmallow

Thanks in advance

**Comment by ghost** [comment]
Have you enabled expert settings and checked DTS-HD? because it sounds like you haven't.

**Comment by ghost** [comment]
Hi Dan,

Yes when I enable DTS-HD I get no sound at all. I think my amp only supports DTS and not DTS-HD.

My Soundbar & Amp Specs: http://www.panasonic.com/uk/consumer/home-entertainment/sound-bars/sc-htb20eb.specs.html

Dolby® Digital yes
Dolby® Pro Logic® II / Dolby® Virtual Speaker    yes
DTS™  yes

Thanks for the reply

**Comment by koying** [comment]
> If i play it with Passthrough IEC and DD & DTS enabled my Amp shows the file as playing DTS

Not sure what's your problem, then...

**Comment by ghost** [comment]
The issue is that IEC works fine. But RAW does not.

If I play a DTS file via IEC I get DTS. If i play a DTS file via RAW i get PCM.

Do you get what I mean?

**Comment by koying** [comment]
Not really. If it works for you in IEC, use IEC.
RAW is only needed for HD audio, that your soundbar doesn't support anyway.

It's explicitly for people having your kind of issues that I added IEC ;)

**Comment by ghost** [comment]
Ok, Thank you very much Koying.

A few people told me that:

IEC was for Shield FW 2.1
RAW for Shield FW 3.0

So was getting a bit confused as I am on 3.0

Thanks for your help. I really appreciate it.

**Comment by koying** [comment]
> A few people told me that:
> 
> IEC was for Shield FW 2.1
> RAW for Shield FW 3.0

Not really, RAW _should_ work on Shield 2.1 as well.
But the combinations between device, AVR/Soundbar and TV are infinite, so choice is King :)

**Comment by ghost** [comment]
Thanks for clearing that up. :-)

**Comment by rfgamaral** [comment]
Not wanting to open a new issue about the same problem, I'm posting this here...

I have almost the same problem as the OP. I have this .mkv file with DTS-HD audio which plays just fine with IEC (my soundbar stream info reports `DTS`) but with RAW, there's no sound at all. The only difference is that my [soundbar is supposed to support DTS-HD](http://www.sony.com/electronics/sound-bars/ht-ct780/specifications).

So, what could be the problem here? I can post a debug log if needed...

**Comment by smhealey** [comment]
I have Vizio P50-C1, NVidia Shield TV and an Enclave Audio Wireless System

Currently connected as:
Shield TV ->(HDMI2 1.4b)Enclave Audio(HDMI Out 1.4b) -> (HDMI1 2.0)Vizio P50-C1)

90% of how I use everything is using SPMC on the Shield TV to play movies from my QNAP TS-453a NAS. 

I currently have video configured: https://github.com/koying/SPMC/wiki/Recommended-video-settings-for-SPMC,-NVIDIA-Shield-TV-and-UHD-(4K)-TVs-with-4K-GUI
I currently have audio configured: https://github.com/koying/SPMC/wiki/Recommended-passthrough-audio-settings-for-SPMC,-NVIDIA-Shield-TV-and-AV-Receivers (except DTS-MA and TrueHD OFF)

My receiver reports passthrough DTS/DD/DD+ audio from SPMC. The Enclave Wireless system can only play DTS-MA or Dolby TruHD if decoded from the Shield TV/SPMC if sent as LPCM5.1.

When  I play TrueHD/DTS-MA with passthrough for these set to OFF in SPMC my receiver still reports as DTS or DD5.1. Shouldn't my receiver report as PCM 5.1 since it is SPMC/Shield TV handling the decoding and sending to my receiver as uncompressed multichannel PCM 5.1 HD audio?

**Comment by classicjazz** [comment]
The Wiki was updated for SPMC v17. I recommend upgrading your SPMC to the 17.6 pre-release

**Comment by smhealey** [comment]
> The Wiki was updated for SPMC v17. I recommend upgrading your SPMC to the 17.6 pre-release

My apologies I just realized this thread was specific to v16.  I am using the newest version from the play store v17.something. Sorry I am not at home to verify the exact version.
