### ISSUE TITLE
Remove caching denial when only audio starves

### ISSUE THREAD

**Issue by koying** [koying/SPMC#252]
https://github.com/koying/SPMC/blob/spmc-jarvis/xbmc/cores/dvdplayer/DVDPlayer.cpp#L1958

**Comment by MrMC** [comment]
eh ?

**Comment by koying** [comment]
Not quite sure. I thought I remembered some code that denied re-caching if only audio starved.
I couldn't find it back, though.

Still something fishy, as there are cases where we starve but not pause+cache. I suspect some edge case, somewhere...

**Comment by MrMC** [comment]
welcome to mr.goldfish syndrome :)

**Comment by koying** [comment]
Yeah ;)
Not sure about the logic of "// don't start caching if it's only a single stream that has run dry", though.

Why? Would that be a symptom of something?

**Comment by MrMC** [comment]
I think the basic assumption is that both audio and video demux buffers 'should' contain a similar amount. That was the entire reason for adding a buffer level reporting that is time based. 

Player splits demux out and passes it to the codec (audio, video, subtitle, etc), then those codecs do their thing. Another assumption is no one is a pig and only eats what it needs to keep in sync. Yea, sure, sure :)

When coming to the end of playback, you can have strange things happen. For example, all the audio demux can get decoded and passed off to AE, the audio demux can be empty but video demux still has some amount left. And player knows nothing except audio demux is empty and starts thrashing.

Or hw video codecs that can drain down video demux buffer because they have their own demux buffers that the player does not know about. 

It starts to get very complicated when dealing with these edge cases. Of course the current god would say, that's wrong and just remove little quirk cases because they get in his way of the master plan :)

Long time ago, I almost had @elupus convinced of allowing codecs to handle their own demux buffers. Maybe time to re-visit that thought.

**Comment by koying** [comment]
Not so goldfish, after all ;)
https://github.com/koying/SPMC/commit/717881d8786dc9129ae2fa0e58cd2b02fd6ae9c7
