### ISSUE TITLE
Question - location of confluence files?

### ISSUE THREAD

**Issue by theVanZan** [koying/SPMC#324]
For the Cinema Experience addon I need to edit the DialogVideoInfo.xml file of Confluence. I could not seem to find its folder....is this deliberate?

I wonder could I manually upload a confluence skin folder to the addons directory of spmc and switch to that and edit it? Would that work?

Thanks!

**Comment by heymoe** [comment]
My guess would have been here:

/sdcard/Android/data/com.semperpax.spmc16/files/.spmc/addons (User level app data dir)

but since Confluence is the default skin included with the APK it likely got installed somewhere in /data (system level app data dir) which can not be accessed unless you have root.

Based on this thread in the Kodi forums, you can create a copy of the Confluence skin with your changes and place that in the user level app dir (see above) and then select your modified version from the available skins.

http://forum.kodi.tv/showthread.php?tid=212533
