### ISSUE TITLE
Remote Home Button 

### ISSUE THREAD

**Issue by molove** [koying/SPMC#329]
Hi
Is there any chance that when using the SPMC launcher that pressing the home button on the Android box remote returns us to the SPMC home page, rather than the SPMC page we left off (usually the Android programs page)? Or is ther a setting I can change somewhere?

Thanks

**Comment by ghost** [comment]
I think the "O" button event on the remote is captured by the Android OS and not propagated down into the app.

You can try remapping the command to the remote using a different button.  But, I hate the Shield TV remote because it has so few buttons.

http://kodi.wiki/view/list_of_built-in_functions

**Comment by mjbxx** [comment]
I'd argue that the Shield remote can do just about all that say a Fire TV remote does when utilizing the long press keymap options. Add in the voice search and ability to control volume and it is leagues better.

**Comment by ghost** [comment]
Being required to long press is poor UX design.

The voice search is nice, but it doesn't work in all apps.

Most people have their volume set to constant and use their TV or AV receiver to control volume.

**Comment by mjbxx** [comment]
At least the option exists for making the Shield remote fully functional. I see no issue with having to long press a button. I only use a universal TV remote to power on/off devices and am quite content with the Shield remote to handle all other functions. I rarely have to use a keyboard because voice recognition handles nearly 100% of all searches within SPMC. This one feature alone makes the Shield remote extremely valuable. And looking forward to voice search for Netflix which should be available soon.

**Comment by ghost** [comment]
But, Nvidia charges 2x more for their remote vs the Amazon Fire TV remote.  The Amazon Fire TV remote has voice search as well and doesn't skimp on the the most basic, required buttons.  Luckily, I got my Nvidia remote for free but if I was to buy one, I'd buy the Amazon Fire TV remote.  Plus, the Amazon Fire TV remote lasts much longer between charges.  The Nvidia remote can barely go 2 weeks without "low battery" warning on the screen.  Ergonomically, the Nvidia remote is so thin, it doesn't feel cradled in the hand.

**Comment by mjbxx** [comment]
Can you even voice search SPMC with the Fire TV remote on the Nvidia Shield TV? If not then that in and of itself is a deal breaker. I've been spoiled rotten with SPMC voice recognition that I'd be lost without it. I'd rather not have to use a keyboard if at all possible. I've gotten 4 plus weeks in between charging and never have to buy batteries. Agree on the ergonomic form factor but I have found it to be more than adequate over time. I got the remote included with the Shield TV but would definitely consider purchasing if I ever have trouble with it.

**Comment by ghost** [comment]
I don't know about that?  Voice search in SPMC is pretty sweet.  That's the main reason why I switched to SPMC from Kodi.

**Comment by koying** [comment]
As stated, the home button is not SPMC-trapable. No way around it.
