### ISSUE TITLE
SPMC crashes on startup when using <pathsubstitution> in advancedsettings.xml

### ISSUE THREAD

**Issue by ghost** [koying/SPMC#336]
I recently tried to use <pathsubstitution> in my advancedsettings.xml but it's causing SPMC to crash immediately after launching?

Here is the pastebin: http://pastebin.com/nrM5KFVC

I followed the instructions on here: http://kodi.wiki/view/MySQL/Sync_other_parts_of_Kodi

The <pathsubstitution> in my advancedsettings.xml in Kodi 16.1 on Windows 10 works fine but it crashes when using it on SPMC 16.3 on Nvidia Shield TV with Android?

**Comment by heymoe** [comment]
Is that the whole log file?

If I had to make a guess at something to try it would be to use the IP of your smb server instead of PANDA and to make sure the smb server does not require authentication and/or IP ACL to access the share.

I could see SPMC crashing due to not being able to access the SMB locations you are path-substituting to.

**Comment by ghost** [comment]
Yes, that's the entire log file.  It crashes very fast right after launching.  I'll try your suggestions and report back.  

I already have SPMC set to save the login/password for my SMB shares.  But, I'm not sure what "IP ACL" means?

Thank you!

**Comment by heymoe** [comment]
IP ACL just means that your smb server is configured to allow specific IP addresses to mount a smb shares without having to authenticate as a user. 

One other things you might try along with what I said earlier is to include your username and password for your smb share in the smb path statement. It's possible that since you're doing path substitutions on configuration files that your saved password info may not be getting loaded at the point the advancedsettings.xml file is being loaded.

Example:
smb://username:password@SERVER-IP/userdata/sources.xml

**Comment by ghost** [comment]
Darn, it still crashed?

http://pastebin.com/xbp6iYps

**Comment by heymoe** [comment]
Hmmm.. So does your advancedsettings.xml file work with the Play Store Kodi version? Granted you'd have to change the local paths to the Kodi paths to test. Wonder if this is specifically a SPMC problem or if Kodi on Android has the same problem. 

You can have both Kodi and SPMC installed at the same time.

**Comment by heymoe** [comment]
One other thing to you could try to debug this. Disable all the path substitutions, start SPMC to make sure it starts. Then enable one substitution at a time to see if there is one that SPMC doesn't like. It could be all of them but maybe we can narrow it down some.

**Comment by ghost** [comment]
I found the path that's making it crash!  It crashes on Kodi as well!

`
        <substitute>    
            <from>special://profile/passwords.xml</from>
            <to>smb://PANDA/userdata/passwords.xml</to>
        </substitute>`

**Comment by heymoe** [comment]
Digging around with this new info and it sounds like other people have run into this same problem and have come to the conclusion that the passwords.xml is not a file that can be substituted:

http://forum.kodi.tv/showthread.php?tid=175694

I also found in this Wiki article under section 1.6 that they specifically say the passwords.xml has to be synced manually if you're using SMB shares.

http://kodi.wiki/view/MySQL/Sync_other_parts_of_Kodi

**Comment by ghost** [comment]
That doesn't surprise me.  It makes sense for security reasons.

Thank you!

**Comment by heymoe** [comment]
No problem.. Please close this issue if all is good now so it doesn't clutter the other open issues. Thanks!
