### ISSUE TITLE
3D movies are played in 2D

### ISSUE THREAD

**Issue by Skydante** [koying/SPMC#348]
Hi everyone!

I have a problem: my 3D movies are played in 2D. There is only one image and my TV does not switch to 3D mode ... The files are named as follows: movie_name 3D SBS.mkv and they are well recognized as 3D files. The video output of the Shield is forced in 1080p 60Hz. Is this is a bug or do I have to adjust something?

Thanks!

**Comment by hannpriv** [comment]
Shield is not able to Play in 3D

**Comment by 99rook99** [comment]
Yes, it does, I watch 3d movies all the time, I just have to set my tv to 3D manually

**Comment by heymoe** [comment]
I know I've played 1080p Half-SBS mkvs and got 3D out of my TV. If you're only seeing a 2D version instead of 2 squished SBS frames then I'm assuming that's why your TV isn't going into 3D mode. I'm not sure about Full-SBS videos. I thought I read something a while ago saying that Kodi/SPMC couldn't play those files (Full SBS) but that was a while ago so maybe things have changed.

**Comment by Skydante** [comment]
I found the answer on the Kodi forum: Go into **Video Settings** → **Acceleration** → disable both **MediaCodec** and **MediaCodec (Surface)**

**Comment by koying** [comment]
Actually, this is done automatically if the video is tagged as 3D: https://github.com/koying/SPMC/commit/47f6294c22654de4b6cffd1b58394a1cccd7cb10

**Comment by Skydante** [comment]
How to correctly name the file ? As I said, the files are named as follows: **movie_name 3D SBS.mkv** and they are well recognized as 3D files (there is an icon next file informations).

**Comment by 99rook99** [comment]
I believe, what koying means is that it turns off hardware acceleration and the 3d is done in software.  I still have to switch my tv to the correct 3d mode.
