### ISSUE TITLE
Weird Netflix Error

### ISSUE THREAD

**Issue by johnnygreen1002** [koying/SPMC#382]
I get a random popup message that says "Netflix has stopped working" when I'm running SPMC. Any way to block this message or correct the issue?  I read that I need to update Netflix and/or Shield firmware but both are current. Thanks.

**Comment by heymoe** [comment]
Not really related to / caused by SPMC unless your SPMC install has a large memory foot print thus the OS (Android TV) is killing things in the background to free up memory in which case maybe you should use a different skin or something that uses less memory but even then it's still not SPMC directly breaking Netflix. More likely the Netflix app is still a bit buggy and they have to fix them.

**Comment by johnnygreen1002** [comment]
Thank you.
