### ISSUE TITLE
Playback crash to SPMC menu issues after Nvidia Shield Update 3.2

### ISSUE THREAD

**Issue by Qpadder** [koying/SPMC#383]
Hi

After the Nvidia Shield 3.2 Update SPMC playback has been very buggy.
Just updated SPMC to 16.4 and still the playback just stops randomly
All files are on my computer and watched over the network. (Windows 10)
Just got myself a new router with DD-WRT hoping the problem would stop. But it has not.

Please help!

Log:

20:02:26 T:1463744816   ERROR: virtual ssize_t XFILE::CSMBFile::Read(void_, size_t) - Error( -1, 22, Invalid argument ) - Retrying
20:02:26 T:1463744816   ERROR: virtual ssize_t XFILE::CSMBFile::Read(void_, size_t) - Error( -1, 22, Invalid argument )
20:02:26 T:1463744816   ERROR: virtual ssize_t XFILE::CSMBFile::Read(void_, size_t) - Error( -1, 22, Invalid argument ) - Retrying
20:02:26 T:1463744816   ERROR: virtual ssize_t XFILE::CSMBFile::Read(void_, size_t) - Error( -1, 22, Invalid argument )
20:02:26 T:1463744816   ERROR: virtual ssize_t XFILE::CSMBFile::Read(void_, size_t) - Error( -1, 22, Invalid argument ) - Retrying
20:02:26 T:1463744816   ERROR: virtual ssize_t XFILE::CSMBFile::Read(void_, size_t) - Error( -1, 22, Invalid argument )
20:02:33 T:1505061168 WARNING: CDVDMessageQueue(audio)::Get - asked for new data packet, with nothing available
20:02:34 T:1504016688 WARNING: CDVDMessageQueue(video)::Get - asked for new data packet, with nothing available
20:02:34 T:1463744816  NOTICE: CDVDPlayer::OnExit()
20:02:34 T:1463744816  NOTICE: DVDPlayer: eof, waiting for queues to empty
20:02:34 T:1463744816  NOTICE: Closing stream player 1
20:02:34 T:1463744816  NOTICE: CDVDMessageQueue(audio)::WaitUntilEmpty
20:02:34 T:1463744816  NOTICE: Waiting for audio thread to exit
20:02:34 T:1505061168  NOTICE: thread end: CDVDPlayerAudio::OnExit()
20:02:34 T:1463744816  NOTICE: Closing audio device
20:02:34 T:1463744816  NOTICE: Deleting audio codec
20:02:34 T:1463744816  NOTICE: Closing stream player 2
20:02:34 T:1463744816  NOTICE: CDVDMessageQueue(video)::WaitUntilEmpty
20:02:34 T:1463744816  NOTICE: waiting for video thread to exit
20:02:34 T:1504016688   ERROR: Got MSGQ_ABORT or MSGO_IS_ERROR return true
20:02:34 T:1504016688  NOTICE: thread end: video_thread
20:02:34 T:1463744816  NOTICE: deleting video codec
20:02:34 T:1390528816  NOTICE: CDVDPlayer::CloseFile()
20:02:34 T:1390528816  NOTICE: DVDPlayer: waiting for threads to exit
20:02:34 T:1390528816  NOTICE: DVDPlayer: finished waiting
20:02:34 T:1390528816  NOTICE: CDVDPlayer::CloseFile()
20:02:34 T:1390528816  NOTICE: DVDPlayer: waiting for threads to exit
20:02:34 T:1390528816  NOTICE: DVDPlayer: finished waiting

**Comment by heymoe** [comment]
I'm not an expert at reading logs but it would seem that SPMC was no longer able to read the file from your network share thus "crashing" / existing back to the main menu.

I'm running SPMC v16.4 + v3.2 Shield TV and SPMC accesses my library over the network via SMB/Samba and I don't have any problems.

If you're running your Shield TV via Wireless I would try and connected it Wired (Ethernet) and see if that fixes the problem. You could also run a ping test from your computer to your Shield TV and see if you're getting packet loss or other network debugging trick since my gut says it's the network and not SPMC.

Personally, I don't recommend running the Shield TV over Wireless. To many variables when it comes to getting a fast and stable connection and someone simply walking between the Shield TV and your WiFi Access Point could throw things into a tizzy.

**Comment by Qpadder** [comment]
It seems like it was my SMB that made the playback crash somehow. I use wired ethernet cable. 
I fixed the problem by using NFS Server. http://www.hanewin.net/nfs-e.htm. 
Works fine now.

**Comment by heymoe** [comment]
Cool cool. I've heard people having better luck with NFS in some cases. I've been using Samba under Linux and it's been fine for me.
