### ISSUE TITLE
SPMC show some files twice

### ISSUE THREAD

**Issue by Schrotty41** [koying/SPMC#384]
Whene the name is xxxx-1080 or xxxx-720 its show me the file twice. Whene i rename to xxxx.1080 or xxxx.720 its all ok. The normal Kodi dont have this issus.
![img_20160716_112238](https://cloud.githubusercontent.com/assets/20558423/16987038/533ad7b6-4e8a-11e6-8afc-888d8d4995ab.jpg)
![img_20160716_112342](https://cloud.githubusercontent.com/assets/20558423/16987046/5c97abae-4e8a-11e6-8e41-fda05acfaecf.jpg)

**Comment by heymoe** [comment]
My guess is that the scrapper is getting confused with how you have the file named when applying the file naming conventions. The e01-720 is being decoded as episode #1 and #720 thus it being showing up twice in the episode list. 

I personally put spaces between the major sections of a file name to limit any confusion of the regex matching when files are being scanned.

Example:
Show Name - s01e01 - Other info and / or episode name.mp4

You using the "." instead of the "-" after the s01 makes the regex match differently thus why it only shows up once with the "."

I personally would recommend using a single file naming scheme for all your files. Based on your example it looks like you just download and stick the resulting file into your library as is without renaming. There are tools out there that will do the renaming for you such as "theRenamer" (google it)

Information related to general file names conventions that Kodi and SPMC use:
http://kodi.wiki/view/Naming_video_files/TV_shows

The other possibility is that you have a custom regex match defined in your advancedsettings.xml file that is causing the mis-matching.

**Comment by Schrotty41** [comment]
I dont have change the advancedsettings.xml. I will test theRenamer but why have the normal Kodi not the problem?

**Comment by heymoe** [comment]
Can't really give you an answer as to why it works fine in Kodi and not SPMC. Maybe Koying made some tweaks to the regex for SPMC that don't exist in Kodi thus the different behavior.

Either way, Kodi and SPMC are two different products. Even though SPMC is based on Kodi, as Koying continues to customize SPMC into what he wants SPMC to be, some direct compatibility between Kodi and SPMC will likely/could change. Plex is based on Kodi and there are difference in file naming conventions between Plex and Koid now too. So, in my mind, the argument that SPMC is broken because XYZ works fine in Kodi is not always a valid argument. 

Maybe Koying will chime in on this thread and maybe he will "fix" or back out the changes that is making SPMC behave differently from Kodi in this case. I've provided you a solution / work around that one would also consider best practices when it comes to managing a library (standardized file naming).  You don't have to do it and wait/hope Koying will fix it for you or you can fix it yourself right now by simply renaming the files. 

Heck you could even define your own custom regex in advancedsettings.xml to support whatever file naming convention you'd like as an alternative way of fixing this too if you wanted.

**Comment by Schrotty41** [comment]
Ok thank you. SMPC is so much better on the Shield TV. I like it.

**Comment by koying** [comment]
I bet you have "include all" enabled, right?
It's probably an edge case of having it enabled AND the regexp picking multiple episodes for the same file.

**Comment by Schrotty41** [comment]
Yes i have but whene i disabled is the same.

**Comment by koying** [comment]
Well, when it's in, it's in.
Disable, remove the two library items and redo a scan, and I bet the file will only appear once

**Comment by Schrotty41** [comment]
Ok working. Thank you.
