### ISSUE TITLE
Please release SPMC to a beta channel in Google Play when it's released as an APK

### ISSUE THREAD

**Issue by classicjazz** [koying/SPMC#388]
Currently, Koying releases SPMC as a downloadable APK when new versions are available (e.g. 16.4). The Google Play version may lag somewhat behind the current release (e.g. right now only 16.3 is available).

Kodi and HdHomerun now use Google Play's beta testing capability. I suggest releasing new versions to a beta tester group via Google Play at the same time as the APK is released to automate deployment to willing testers, while still delaying release of the latest version to all Android users via Google Play until it is deemed stable.

**Comment by gpmc01** [comment]
16.4.0 not available yet in Play Store.....sigh

**Comment by 99rook99** [comment]
That is because there were fixes that needed to be made to it, Koying is now working on 16.4.1.

**Comment by gpmc01** [comment]
Noted. Thanks

**Comment by johnnygreen1002** [comment]
Should we stick to 16.3 then?

**Comment by 99rook99** [comment]
16.4.1 is now available

**Comment by heymoe** [comment]
Beta channel or not, If you really want to run the latest version just side load the APK from the website.

Honestly if you're the type of person that's monitoring the website to see if a new version is out every day so you can run the latest and greatest instead of just letting the updates roll-out via the Play Store, then learning how side load an APK is in general something you should learn how to do any ways. Just my opinion.

**Comment by classicjazz** [comment]
It's not a question of whether one knows how to sideload an APK. It's a matter of convenience when testers like me have multiple Shield TVs and don't want to fire up ES Explorer, Transmit, etc. for each Shield (or whatever Android STB). Having a beta test auto-deployment ensures that every tester is using the latest version. And its common practice in mobile software development, Kodi, Google Maps, HDHomerun, etc.

**Comment by heymoe** [comment]
It's up to the developer (Koying) if they want to use the Beta Channel feature of the Play Store. I honestly don't know if Koying has a formal group of "testers" or if he just relies on the people that know how to install the latest APKs to test and report to the forums. 

Since this is something he does in his free time, maybe having to deal with setting up and maintaining a Beta Channel is more than he wants to do right now and having a hardcore set of people willing to go the extra mile to install the latest APK is the preferred set of testers he wants to deal with instead of giving everyone an easy way to install the latest "Beta" by joining the Beta channel who will just complain that it doesn't work and not provide any useful debugging information.

Personally downloading the latest APK from the website and issuing two adb commands per Shield TV device to install the new APK over the network isn't all that much work and can be scripted / automated. Maybe that is something you should look into instead of doing all of that copying / USB stick transfers / ES File Explorer mess.

**Comment by BlindfoldNL** [comment]
Or just use the Nvidia Shield TV Utility app to even do the adb commands for you for extra lazy one click action. Everytime a new version is out I like to read the changenotes before updating anyway, so I don't really mind the current way of updating.
