### ISSUE TITLE
Broken Multi Episode

### ISSUE THREAD

**Issue by jarlave** [koying/SPMC#56]
If i have an mp4 file that includes 2 episodes E21 & E22
I name it S02E21E22 and in the nfo there are 2 <episodedetails> with epbookmarks

But in SPMC (14.2) it shows only episode E21, this works in Kodi 14.2

please fix this

**Comment by war59312** [comment]
Been broken since Sept. 2014 sadly.

See: https://github.com/koying/SPMC/issues/17

Also, see: http://ouyaforum.com/showthread.php?8220-SPMC-Koying&p=152879&viewfull=1#post152879

Fix Is Here: https://github.com/xbmc/xbmc/pull/5485

Update: It's already fixed in the current code. So should be fixed in next release. Or could build it now?

**Comment by jarlave** [comment]
Still broken in SPMC 15
