### ISSUE TITLE
Nvidia shield... Should I set shield HDMI setting to 1080p or 4K?

### ISSUE THREAD

**Issue by willsy555** [koying/SPMC#709]
Hi

Just got my brand new Nvidia shield and have been looking at Kodi/SPMC.

I love it!!

Could I ask a question of the experts though!

With regard to UI display settings, there are two options I understand:

1) set the nvidia shield to 1080p and get 1080p menus. The TV then upscales to 4K.
2) set the nvidia shield to 4K and get 4K menus and screen, but Kodi/Shield upscales to 4K.

I mainly watch 1080p content at the moment (usually blu ray material) so I guess the best option will be to set to 1080p.

I wondered though, is the Kodi upscale a lot worse than a modern 4K TV upscale?

Could probably try this out myself and compare it, but wondered if anyone else has tried this and compared?

Would be nice to have a 4K UI for Kodi and for the Shield in general. If there's not much in it, then it might be worth it...

Cheers

Will.

**Comment by classicjazz** [comment]
Several thoughts based on SE5.01 and SPMC 16.5.5:

* Assuming that you have a high speed internet connection and a 4K TV, there is a lot of 4K and some HDR content available outside of SPMC including Youtube, Netflix, Amazon, and others. So if you watch content from these providers, you will want to use the Shield's recommended 4K/59.94 setting.

* The Shield's Leanback Launcher is in upscaled 1080 not 2160p.

* SPMC (and Kodi 17) support 4K GUI. How good this looks depends on (1) how high resolution your jacket art and episode thumbnails sources are and (2) how big this jacket art is displayed in your skin. If you are using 4K for other reasons on the Shield, then it makes sense to enable 4K GUI in SPMC because there isn't a meaningful performance hit.

* Enabling HQ scalers makes a big difference for SPMC's 4K upscaling capabilities though it likely doesn't look as good as your HDTV's upscalers. You can easily test this. There were performance issues in 16.5 series that seem better with SE5.x, 16.6beta, IEC enabled, and removal of ES Explorer.

@koying should comment about whether he has/will enable display resolution switching for SE5.x in 16.6. I personally haven't seen it in action in beta1 yet. If so, this would be the best compromise for Shield users.

**Comment by koying** [comment]
Resolution switching (as in change resolution inside SPMC) doesn't work in my preview 5.0 for 2015. Selecting 1080p keep the Shield in 4K.
It's whether a Shield bug that will be corrected in final , an SPMC bug or something that is just not meant to work.

I'll wait for the final FW to investigate further.

**Comment by classicjazz** [comment]
@koying 

I have 5 '17 Shields and SE5.01. 2 are connected to '16 Vizio P series Smartcast TVs; 3 to '15 M series 4K TVs. On the Smartcast TVs, I can monitor real time display data using their mobile app. If there is additional testing that I can do, please let me know. 

I assume that it will be straightforward--play 480i, 720p, 1080i, 1080p content and see if the Shield switches from 4K down to native resolution while content is playing.

**Comment by willsy555** [comment]
Thanks guys... It would be awesome to have that switching functionality... I'll keep my fingers crossed that it's coming soon! :-)

**Comment by classicjazz** [comment]
@koying 

Shield Experience 5.02 for 2015 models was just released...

**Comment by jspuds1** [comment]
This would be my preferred setup as well, Shield running 4k for Netflix etc and 1080p for SPMC.
Would it be possible to share the settings for this configuration?

**Comment by classicjazz** [comment]
@jspuds1 
Since applications based resolution switching is not yet available, you should use either the 4K Wiki recommendations (in which case, SPMC will output at 4K or use the 1080p Wiki recommendations (but that assumes that every app is forced to output at 1080p too)

**Comment by jspuds1** [comment]
Thanks Classicjazz
