### ISSUE TITLE
Shield Experience 5.1 + TrueHD/DTS-HD = SPMC crash

### ISSUE THREAD

**Issue by iipamonkey** [koying/SPMC#775]
Since upgrading to 5.1 yesterday (and restarting the Shield a couple times thereafter),  SPMC crashed the first time I played files with each of these audio formats. In both cases I closed SPMC, went back and played the file again, and it worked OK.

Feel free to close if I'm the only one ever reporting/experiencing this, but just thought I'd mention it in case there are others out there and they happen to chime in.

I did send the crash report to SPMC via the in-app interface for the DTS-HD crash.

**Comment by heymoe** [comment]
I personally have not run into this issues and I've recently watched a few videos with TrueHD+Atmos and DTS-HD on my Shield TV with v5.1 installed. Did you setup SPMC using the recommend Shield TV settings in the Wiki?

https://github.com/koying/SPMC/wiki#Nvidia_Shield_Specific

It should be noted that I'm not running the latest SPMC which looks to be 16.5.5. I'm still on 16.4.2 mainly because I've been lazy to update. It does look like v16.5.5 has some specific Shield TV crash fixes if you're not running it already.

**Comment by iipamonkey** [comment]
Yes, I had configured all settings as recommended in the wiki for my setup (Shield + AVR) and was running SPMC 16.5.5 and SE 5.1.

The crash only happened the first time I tried playing each of those formats and hasn't happened since. Since it's not really reproducible and nobody else seems to have experienced it, I will go ahead and close the issue. I see other crashes very rarely after I've adjusted one setting or another, so this was probably just some fluke similar to that.
