### ISSUE TITLE
Auto Refresh Rate and HDR

### ISSUE THREAD

**Issue by jaycronik** [koying/SPMC#813]
Is there any way to get HDR working with auto refresh rate = on ?
With 60Hz i've got micro stutter.

**Comment by wweich** [comment]
Sure, I just did that with a movie.
Before this works, you need to set the shield settings to 23.976Hz and than the color to `YCbCr 4:2:2 12Bit REC2020` in the advanced settings. Then you can set it back to 60Hz.
This will result in *auto refresh rate switches* to rates below 50Hz to have YCbCr with Rec2020 instead of RGB. Only YCbCr with Rec2020 can do HDR.

*This needs Shield Experience V 5.x*

**Comment by jaycronik** [comment]
Thanks, did that works fine!
