### ISSUE TITLE
Nvidia controller not working in SPMC

### ISSUE THREAD

**Issue by Nebuchanezzer** [koying/SPMC#836]
Hi all!

After the last update the Nvidia game-controller stopped working inside SPMC.

It works just fine until I open SPMC after that the only button still working is the "home"-button (jumps out of SPMC).

Anyone know what to do here?

**Comment by Rohazon** [comment]
Hello,
i believe it's due to some nvidia update for remote that's fail on reboot, I had this problem among others.
go to nvidia setting remote section, delete your controller, then press (in setting not controller)  to scan for new device and on your controller, press 15 seconds the nvidia button (this should reset the controller) and it should be back and running again,
Hope this will work for you too

**Comment by Nebuchanezzer** [comment]
Sorry for late reply, I've been away for bit.

That was actually one of the first things I tried (twice), but with no luck.

Anyway, I decided to try it one more time when I got home, and what do you know this time it worked!

Thank you!
