### ISSUE TITLE
Dolby or dts not work, get only multi channel

### ISSUE THREAD

**Issue by Schrotty74** [koying/SPMC#845]
I have connect my Shield TV 2017 on a Denon X2200W AVR and use the Settings from here https://github.com/koying/SPMC/wiki/Recommended-passthrough-audio-settings-for-SPMC,-NVIDIA-Shield-TV-and-AV-Receivers . But i get only PCM Multi Channel Output, normal i see dd, dts or truehd.

**Comment by Schrotty74** [comment]
With v16.5 i get dd, dts and truehd but with 16.6 i get only multi pcm.

**Comment by craigtaranto** [comment]
This won't be much help, but I will say that I get DD, DTS, DTS-MA, TrueHD, etc. on my Denon x3300w using  16.6.0 on an nVidia Shield 2015 (with latest 5.1 Experience) and using the same instructions as you linked.

I suggest double checking all settings (esp. making sure Passthrough is enabled).

I will say that using IEC (instead of RAW) is fixed my audio syncing issues when fast forwarding content.

**Comment by barenaked** [comment]
Same here, passthrough with the IEC protocol works just fine on my Pioneer VSX-S520. Check your settings or connections  again.

**Comment by classicjazz** [comment]
Are you using the latest receiver firmware? I read that for some Denon/Marantz models, updating the latest firmware solves IEC issues.

**Comment by Schrotty74** [comment]
Its working now. Have use recomment Settings for 4k.
