### ISSUE TITLE
Exodus no longer supporting 16.1 jarvis! 

### ISSUE THREAD

**Issue by JFG90** [koying/SPMC#851]
So I've just read exodus no longer will be supporting 16.1 :( will there be spmc 17?

**Comment by lukehansford** [comment]
I posted an issue about the lack of SSL in Jarvis and most providers are starting to use SSL addresses which means it's only a matter of time till spmc based on kodi 16 will lose all sources from addons not just exodus. Compare the links you get with kodi 17 on exodus to confirm this. The pulse build dev said he won't move over to kodi 17 untill spmc updates. The lack of pulse and lack of voice control on kodi 17 is stopping me moving to kodi 17. If spmc would update it would fix all issues we will start to see with the old 16.1

**Comment by lukehansford** [comment]
http://koditips.com/kodi-exodus-not-working-click-here-for-info/

Explains the issu we all face now on spmc. We need spmc to move to the Kodi 17 base asap which will fix this and other issues such as random crashing on exit

**Comment by JFG90** [comment]
I've tried 3 other addons tonight and they are all slow and un responsive I'm gonna have to switch to 17 until it's sorted i think

**Comment by JFG90** [comment]
Can't even switch to 17, it won't accept my build i made

**Comment by ruppert10** [comment]
I just installed kodi version 17.1 to fix this issue it is a issue with 3 other addons as well that are clones of exodus the sp***o addon and the z*n addon the only way to fix it is to get kodi 17.1 then in all 3 addons 
( if you have all 3 that is ) you have to go into them one at a time and clear providers and cache then restart kodi and its all fixed i am glad if this helps people on here out but my real reason for commenting here today is to beg and plead with koying to get his version of spmc 17 out because the kodi 17 is running like crap it takes forever to close so bad sometimes that after 3-5 minutes i have to force close it or it will just crash it is just not fast and responsive like koyings spmc i just know that when his version is finaly out it will run like lightning and will close fast and not crash i have 3 mi boxes and kodi runs so bad on them but my spmc 16.60 runs circles around kodi on the mi boxes but to fix the addons for now we all have to run kodi koying thank you for everything you do i can't wait until your version is out thanks again

**Comment by wrxtasy** [comment]
I doubt a (ex)Kodi developer like Koying will even care about helping or supporting your Kodi Piracy Addons - if they work or not.

Kindly take you discussion elsewhere and have some respect for Koying - SPMC and the Kodi project. !

**Comment by JFG90** [comment]
How about you don't be so rude, none of us have said we don't respect koying! Just stating that alot of addons are slowly not being supported by 16.1 there was a statement online about it the other day! Tool !
