### ISSUE TITLE
Mixing SPCM 16.6.0 with Kodi 17; MySQL DB?

### ISSUE THREAD

**Issue by mattspew** [koying/SPMC#857]
I run the semi-support external MySQL database for Kodi in my house. Current database version is 16 for Kodi 16.1 and SPMC 16.6.0. 

I'd like to update my two PCs to Kodi 17, knowing this will update my MySQL database for Kodi 17, will SPMC 16.6.0 use the Kodi 17 database or point at the older version which the upgrade leave behind.

Thanks.

**Comment by heymoe** [comment]
Unless something has changed in how the DB updates work, the Kodi 17 installs will upgrade your current v16 DB by creating a new v17 DB. So you will basically have 2 separate databases, one v16 version that SPMC will continue to use and a new v17 version that the Kodi v17 installs will use. 

Basically each version of Kodi/SPMC will use the DB table schema/version that they are designed to use.

http://kodi.wiki/view/database_versions 

This of course defeats the purpose of using a MySQL DB since you can't just updated on DB and all Kodi/SPMC installs will see the changes (new content, watched status, etc..). So if you upgrade your PCs yuor v17 you'll have to at least send library update / refresh commands to one SPMC device and one Kodi v17 device. Keeping other things in sync like watched statuses might be a little trickier. I think you can use the Trakt add-on though to act as your centralized watch database though.

**Comment by mattspew** [comment]
Nothing has changed, that's exactly how an upgrade works, I know I'd end up with a table for each version.

My question wasn't worded well and I should have asked; can I force SPMC 16.6.0 to use a v17 database?

**Comment by heymoe** [comment]
I'm sure there is a way to trick it into using the v17 DB but likely will result in a number of issues depending on how much the DB schema has changed between v16 and v17.  Pretty sure it wound't be recommended.

**Comment by mattspew** [comment]
I'm not in the mood for an unstable media player....

Guess I'll just wait patiently for SPMC to catch up.
