### ISSUE TITLE
How to set default skin

### ISSUE THREAD

**Issue by handagen** [koying/SPMC#864]
Hello everyone，

I made a flat version of the Android, When SPMC16.5.1 is installed, the default skin shown is skin.re-touched，I would like to ask is:
1，how to force the default skin set skin.confluence
2，SPMC from the platform to get what information, it is decided to use the default skin，In this case, I can also send a message to the SPMC TV, the SPMC default skin will choose skin.confluence

**Comment by mo123** [comment]
@handagen All Amlogic devices with shitty firmware has this problem since they report they are a tablet and not a tv box. It's not a problem from SPMC's side but rather from your tv box's software.
This problem was reported several times ago in SPMC's issues and that it is a firmware problem.
Only thing you can do is change the skin manually.
Or if you have skills to compile SPMC yourself you can change all the references to the skin you want to use.

**Comment by bravado07** [comment]
odd that it (SPMC) wouldnt default to just 1 skin vs implementing code to determine and default 2 different skins.  Tinkering with it now, lets see how far i get

**Comment by handagen** [comment]
If I use a table version of the device, and I do not compile SPMC, How do I modify the platform code, the default skin for SPMC selection is skin.confluence。

Best Regards.
